const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
const packageType = [
  "Bed and Breakfast",
  "Breakfast Included",
  "Complimentary Breakfast",
  "Breakfast Buffet",
  "Continental Breakfast",
  "Full American Breakfast",
  "Room with Breakfast",
];
const googleDriveFolder = ["1AOvCHNgd97zu6uRGa0MSyEThXqRLF7CH"];
const sessionSecretKey='SDkalsjdlasd20)(**)(*&%^^$UWG!@$GHgjhjGSHJGD675';
module.exports = {
  months: months,
  states: states,
  packageType: packageType,
  googleDriveFolder: googleDriveFolder,
  sessionSecretKey:sessionSecretKey
};
